USE test_new;
CREATE TABLE Persons (Personid int NOT NULL auto_increment, FirstName varchar(30), Lastname varchar(30) NOT NULL, Age int, primary key (Personid));
INSERT INTO Persons (FirstName,Lastname) VALUES ('Ashish', 'Jha');
SELECT * FROM Persons;
SELECT * from limbs;
USE World;
SELECT * FROM city;
SELECT Name, District FROM city;
SELECT DISTINCT CountryCode From city;
SELECT * FROM city;
SELECT Name, Population/1000 FROM city;
SELECT * FROM city WHERE Population>1000000 AND Population<1500000;
SELECT * FROM city Where CountryCode IN('AUS','AFG');
SELECT * FROM city Where CountryCode LIKE 'A%';
SELECT * FROM city order by Population DESC;
SELECT * FROM city order by CountryCode DESC, Population DESC;
SELECT count(Name) as totalcity FROM city;
SELECT sum(Population) as total_pop From city;
SELECT * FROM country;
Select * From city;
Select a.Name, a.Population, b.Region From city a, country b Where a.CountryCode=b.Code;
Select a.Name, a.Population, b.Region, c.Language From city a, country b, countrylanguage c Where a.CountryCode=b.Code AND a.CountryCode=c.CountryCode;